### ISSUE TITLE
When training the model, it stops at a level far below a given epoch.

### ISSUE THREAD

**Issue by Choikyungho9** [autorope/donkeycar#946] opened 2021-10-20 15:43 UTC
![donkey_train](https://user-images.githubusercontent.com/20491139/138125796-5bafbe31-d67f-47e4-b678-d77ca9dd4430.jpg)

When training data, the trained model is created as the training ends without filling the set epoch.

If you look at the attached picture, the total epoch is 100, and it stops at the 10th training.

How do I fill in 100 trainings of my model?

**Comment by Ezward** [comment] 2022-01-15 06:04
Early stopping is a feature.  I'm closing this as 'as intended'.

**Closed by Ezward** 2022-01-15 06:04 UTC
