### ISSUE TITLE
Conda environment file (windows.yml) for Windows somehow got dropped in Dev

### ISSUE THREAD

**Issue by zlite** [autorope/donkeycar#727] opened 2021-01-06 05:58 UTC
[This folder](https://github.com/autorope/donkeycar/tree/dev/install/envs) should have windows.yml as described in the docs [here](http://docs.donkeycar.com/guide/host_pc/setup_windows/)

**Comment by Hyunwoo-Park-Yonsei** [comment] 2021-01-11 06:15
Having same error. Did you find windows.yml file?

**Comment by Hyunwoo-Park-Yonsei** [comment] 2021-01-11 06:23
I have found window.yml file. 
Go to below link and download the relaese 3.1 and there is windows.yml
https://github.com/autorope/donkeycar/releases

**Comment by tikurahul** [comment] 2021-01-11 07:49
We no longer need a `windows.yml` file. Please use `ubuntu.yml` for now. That should get renamed to `pc.yaml` as there are no x-platform differences.

**Comment by custom-build-robots** [comment] 2021-01-12 05:17
@tikurahul today I tested once again the "ubuntu.yml" file on my Windows 10 laptop with conda and we hat a short discussion on discord. The problem is that tensorflow 2.2.0 is not available for conda.
If you use the ubuntu.yml installation file then you have to change the tensorflow version to 2.3.0. or 2.1.0 due to the fact that 2.2.0 is not available...

**Comment by tikurahul** [comment] 2021-01-12 05:20
We can switch to 2.3.0.

**Comment by DocGarbanzo** [comment] 2021-01-16 15:00
I've updated the `ubuntu.yml` to allow tf >= 2.2.0 <= 2.3.2. I'll do a PR to rename the file to `pc.yml` and update the docs.

**Comment by DocGarbanzo** [comment] 2021-01-16 20:04
Addressed in #748.

**Closed by DocGarbanzo** 2021-01-16 20:04 UTC
